options = {
    "A": {"key": "AA"},
    "B": {"key": "BB"},
    "C": {"key": "CC"},
    "D": {"key": "DD"},
    "E": {"key": "EE"},
    "F": {"key": "FF"},
    "G": {"key": "GG"},
    "H": {"key": "HH"},
    "I": {"key": "II"},
    "J": {"key": "JJ"},
    "K": {"key": "KK"},
    "L": {"key": "LL"},
    "M": {"key": "MM"},
    "N": {"key": "NN"},
    "O": {"key": "OO"},
    "P": {"key": "PP"},
    "Q": {"key": "QQ"},
    "R": {"key": "RR"},
    "S": {"key": "SS"},
    "T": {"key": "TT"},
    "U": {"key": "UU"},
    "V": {"key": "VV"},
    "W": {"key": "WW"},
    "X": {"key": "XX"},
    "Y": {"key": "YY"},
    "Z": {"key": "ZZ"},
    "Space": {"key": "SP", "code": b"\x2C"},
    "Esc": {"key": "ES", "code": b"\x29"},
    ";": {"key": ";;", "code": b"\x33"},
    "Left": {"key": "LE", "code": b"\x50"},
    "Right": {"key": "RI", "code": b"\x4F"},
    "Up": {"key": "UP", "code": b"\x52"},
    "Down": {"key": "DO", "code": b"\x51"},
    "Delete": {"key": "DE", "code": b"\x4C"},
    "ShiftRight": {"key": "SR", "code": b"\xE5"},
    "ShiftLeft": {"key": "SL", "code": b"\xE1"},
    "Tab": {"key": "TA", "code": b"\x2B"},
}
